# Changes here will be overwritten by Copier
AddAllcontributors: false
AddCitationCFF: false
AddCodeOfConduct: false
AddCompatHelperCI: true
AddCopierCI: false
AddDependabot: false
AddDocs: false
AddDocsCI: false
AddFormatterAndLinterConfigFiles: false
AddGitHubPRTemplate: true
AddGitHubTemplates: false
AddLintCI: false
AddLychee: false
AddMacToCI: false
AddTagBotCI: true
AddTestCI: true
AddWinToCI: false
Authors: Cas Bex <cas.bex@kuleuven.be>
AutoIncludeTests: false
CheckExplicitImports: false
JuliaMinCIVersion: '1'
JuliaMinVersion: '1'
License: MIT
LicenseCopyrightHolders: Lucas Bex
PackageName: ZMQLoggers
PackageOwner: JuliaLogging
PackageUUID: e9bc4a15-d3b7-45db-a26a-813125f6ff30
RunJuliaNightlyOnCI: false
StrategyConfirmIncluded: true
StrategyLevel: 1
StrategyReviewExcluded: false
UseCirrusCI: false
_src_path: /home/cas/.julia/packages/BestieTemplate/jdG8v
